# Generated by Django 6.0.4 on 2026-04-15 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('total_spent', models.FloatField(default=0)),
                ('last_transaction_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_dynamic', models.BooleanField(default=True)),
                ('rules', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SegmentDelta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.JSONField()),
                ('removed', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.segment')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='core.segment')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.segment')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.segment')),
            ],
            options={
                'unique_together': {('segment', 'customer')},
            },
        ),
    ]
